name: c-linter

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      # Push events on main branch
      - main
jobs:
  c-linter:
    name: c-linter
    runs-on: ubuntu-latest
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
          
      - name: c-linter
        uses: ArtificialAmateur/cpp-linter-action@0.01
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
