name: PR AutoTag
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      # Push events on main branch
      - main
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: ArtificialAmateur/cpp-linter-action@0.01
